### PR TITLE
Unify gitignores, add logs folder

### PR DESCRIPTION
**Pull request by joaociocca**
I may be missing something, but I don't think there's a need for different .gitignore files. Also, there's no reason for the logs folder to be monitored for changes, and adding it recursively makes things simpler.

### CODE REVIEW

**Comment by ManofWax** [comment]
Hi Joao, git does not track empty folders. So the multiple `.gitignore` inside `pcaps`, `logs` etc. have a double function: to let git keep track of the folder and also ignoring future files that will be saved there.

By unifing them in a file on the root of the project git won't track the directory anymore.

**Comment by joaociocca** [comment]
argh, I completely forgot about that! Still, an empty .gitignore would do the trick of tracking those empty needed folders, while the ignore configuration could be centralized in the project's root folder, making it easier to manage what is and what isn't ignored, no?

**Comment by ManofWax** [comment]
Yeah It could make sense. Git recomends using empty `.gitkeep` files instead of `.gitignores` to do this trick. Can you add those so I can merge the pull request?

Thanks

**Comment by joaociocca** [comment]
~~already done on 0e20002~~

ops! I had recreated the `.gitignore` files yesterday, instead of those `.gitkeep` ones. Let me adjust that.

**Review by ManofWax — APPROVED** [review]

**Pull request merged**
